// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef colourchoice_h
#define colourchoice_h
#include <FL/Fl.H>
#include <FL/gl.h>
class TBmeshWin;
#include "FL/Fl_Check_Browser.H"
#include "Surfaces.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Color_Chooser.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>

class colourChoice {
public:
  colourChoice( GLfloat *c, Fl_Check_Browser *cb, Object_t o, TBmeshWin *t );
  Fl_Double_Window *window;
  Fl_Color_Chooser *rgb_choice;
private:
  inline void cb_rgb_choice_i(Fl_Color_Chooser*, void*);
  static void cb_rgb_choice(Fl_Color_Chooser*, void*);
public:
  Fl_Slider *opacity;
private:
  inline void cb_Done_i(Fl_Return_Button*, void*);
  static void cb_Done(Fl_Return_Button*, void*);
public:
  Fl_Button *apbut;
private:
  inline void cb_apbut_i(Fl_Button*, void*);
  static void cb_apbut(Fl_Button*, void*);
  Fl_Check_Browser *ch_br; 
  Object_t obj; 
  TBmeshWin *tbmw; 
};

class AuxColourChoice {
public:
  AuxColourChoice( GLfloat *c, Object_t o, TBmeshWin *tb);
  Fl_Double_Window *window;
  Fl_Color_Chooser *rgb_choice;
private:
  inline void cb_rgb_choice1_i(Fl_Color_Chooser*, void*);
  static void cb_rgb_choice1(Fl_Color_Chooser*, void*);
public:
  Fl_Slider *opacity;
private:
  inline void cb_Done1_i(Fl_Return_Button*, void*);
  static void cb_Done1(Fl_Return_Button*, void*);
public:
  Fl_Button *apbut;
private:
  inline void cb_apbut1_i(Fl_Button*, void*);
  static void cb_apbut1(Fl_Button*, void*);
  GLfloat *col; 
  Object_t obj; 
  TBmeshWin *tbmw; 
};
#endif
