// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef colourchoice_h
#define colourchoice_h
#include <FL/Fl.H>
#include <Fl/gl.h>
#include "TBmeshWin.h"
#include "Surfaces.h"
#include <FL/Fl_Double_Window.H>
#include <Fl/Fl_Color_Chooser.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>

class colourChoice {
public:
  colourChoice( GLfloat *c, bool *b, int nb, Object_t o, TBmeshWin *t );
  Fl_Double_Window *window;
  Fl_Color_Chooser *rgb_choice;
  Fl_Slider *opacity;
private:
  void cb_Done_i(Fl_Return_Button*, void*);
  static void cb_Done(Fl_Return_Button*, void*);
public:
  Fl_Button *apbut;
private:
  void cb_apbut_i(Fl_Button*, void*);
  static void cb_apbut(Fl_Button*, void*);
public:
  ~colourChoice();
private:
  GLfloat *col; 
  int numreg; 
  Object_t obj; 
  TBmeshWin *tbmw; 
  bool *sc; 
};

class AuxColourChoice {
public:
  AuxColourChoice( GLfloat *c, Object_t o, TBmeshWin *tb);
  Fl_Double_Window *window;
  Fl_Color_Chooser *rgb_choice;
  Fl_Slider *opacity;
private:
  void cb_Done1_i(Fl_Return_Button*, void*);
  static void cb_Done1(Fl_Return_Button*, void*);
public:
  Fl_Button *apbut;
private:
  void cb_apbut1_i(Fl_Button*, void*);
  static void cb_apbut1(Fl_Button*, void*);
  GLfloat *col; 
  Object_t obj; 
  TBmeshWin *tbmw; 
};
#endif
