// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef HDF5DataBrowser_h
#define HDF5DataBrowser_h
#include <FL/Fl.H>
#ifdef USE_HDF5
#include "ch5/ch5.h"
#endif
#include "TBmeshWin.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Return_Button.H>

class HDF5DataBrowser {
public:
  HDF5DataBrowser( const char *fn, TBmeshWin *meshwin );
  Fl_Double_Window *hdf5dataWin;
  Fl_Browser *nodDatBrows;
  Fl_Browser *vecDatBrows;
  Fl_Browser *auxGridBrows;
  Fl_Browser *dynPtBrows;
private:
  inline void cb_Read_i(Fl_Return_Button*, void*);
  static void cb_Read(Fl_Return_Button*, void*);
  inline void cb_Close_i(Fl_Return_Button*, void*);
  static void cb_Close(Fl_Return_Button*, void*);
  inline void cb_Clear_i(Fl_Return_Button*, void*);
  static void cb_Clear(Fl_Return_Button*, void*);
public:
  void process_selections();
private:
  TBmeshWin *tbmw; 
  string file; 
#ifdef USE_HDF5
  hid_t hdf_in; 
#endif
};
#endif
