// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef Sequence_h
#define Sequence_h
#include <FL/Fl.H>
#include "TBmeshWin.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Input.H>

class Sequence {
public:
  Sequence( TBmeshWin *tb );
  Fl_Double_Window *window;
  Fl_Progress *movieprog;
private:
  void cb_Start_i(Fl_Return_Button*, void*);
  static void cb_Start(Fl_Return_Button*, void*);
public:
  Fl_File_Input *fname;
private:
  void cb_browse_i(Fl_Button*, void*);
  static void cb_browse(Fl_Button*, void*);
public:
  Fl_Value_Input *lastFrameNum;
private:
  TBmeshWin *mwtb; 
};
#endif
