/*
  File autogenerated by gengetopt version 2.22.4
  generated with the following command:
  gengetopt -u --default-optional

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: igbhead [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                 Print help and exit",
  "  -V, --version              Print version and exit",
  "  -x, --x=INT                number of x pixels",
  "  -y, --y=INT                number of y pixels",
  "  -z, --z=INT                number of z pixels",
  "  -t, --t=INT                number of time slices",
  "  -d, --data-type=STRING     char byte int uint float long double vec3f vec4f \n                               vec3d vec4d OR rgba",
  "  -s, --system=STRING        big_||little_endian",
  "  -X, --dim-x=FLOAT          Size in x",
  "  -Y, --dim-y=FLOAT          Size in y",
  "  -Z, --dim-z=FLOAT          Size in z",
  "  -T, --dim-t=FLOAT          Duration",
  "  -5, --fac-x=FLOAT          Scaling factor in x",
  "  -6, --fac-y=FLOAT          Scaling factor in y",
  "  -7, --fac-z=FLOAT          Scaling factor in z",
  "  -8, --fac-t=FLOAT          Scaling factor in t",
  "  -o, --org-x=FLOAT          Origin for x",
  "  -p, --org-y=FLOAT          Origin for y",
  "  -q, --org-z=FLOAT          Origin for z",
  "  -r, --org-t=FLOAT          Origin for t",
  "  -I, --inc-x=FLOAT          Increment in x",
  "  -J, --inc-y=FLOAT          Increment in y",
  "  -K, --inc-z=FLOAT          Increment in z",
  "  -L, --inc-t=FLOAT          Increment in t",
  "  -S, --data-factor=FLOAT    Scaling factor for data",
  "  -0, --data-zero=FLOAT      Origin for data scaling",
  "  -A, --author=STRING        Author name with no spaces",
  "  -u, --units=STRING         Data units",
  "  -1, --x-units=STRING       Units for x",
  "  -2, --y-units=STRING       Units for y",
  "  -3, --z-units=STRING       Units for z",
  "  -4, --t-units=STRING       Units for t",
  "  -j, --jive-time            Make no. time slices jive with data size",
  "  -e, --transparent=STRING   Transparent pixel value in hex",
  "  -E, --no-transparent       Turn transparency off",
  "  -D, --decapitate           Remove header",
  "  -c, --comment=STRING       Add a line of comment",
  "  -C, --clear-comment        Clear all comments",
  "  -f, --output-file=STRING   output file",
  "  -F, --frankenstein=STRING  attach header to this file",
  "  -l, --explode              explode file into igb time slices",
  "  -m, --memfeminize          convert igb to memfem format",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->x_given = 0 ;
  args_info->y_given = 0 ;
  args_info->z_given = 0 ;
  args_info->t_given = 0 ;
  args_info->data_type_given = 0 ;
  args_info->system_given = 0 ;
  args_info->dim_x_given = 0 ;
  args_info->dim_y_given = 0 ;
  args_info->dim_z_given = 0 ;
  args_info->dim_t_given = 0 ;
  args_info->fac_x_given = 0 ;
  args_info->fac_y_given = 0 ;
  args_info->fac_z_given = 0 ;
  args_info->fac_t_given = 0 ;
  args_info->org_x_given = 0 ;
  args_info->org_y_given = 0 ;
  args_info->org_z_given = 0 ;
  args_info->org_t_given = 0 ;
  args_info->inc_x_given = 0 ;
  args_info->inc_y_given = 0 ;
  args_info->inc_z_given = 0 ;
  args_info->inc_t_given = 0 ;
  args_info->data_factor_given = 0 ;
  args_info->data_zero_given = 0 ;
  args_info->author_given = 0 ;
  args_info->units_given = 0 ;
  args_info->x_units_given = 0 ;
  args_info->y_units_given = 0 ;
  args_info->z_units_given = 0 ;
  args_info->t_units_given = 0 ;
  args_info->jive_time_given = 0 ;
  args_info->transparent_given = 0 ;
  args_info->no_transparent_given = 0 ;
  args_info->decapitate_given = 0 ;
  args_info->comment_given = 0 ;
  args_info->clear_comment_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->frankenstein_given = 0 ;
  args_info->explode_given = 0 ;
  args_info->memfeminize_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->x_orig = NULL;
  args_info->y_orig = NULL;
  args_info->z_orig = NULL;
  args_info->t_orig = NULL;
  args_info->data_type_arg = NULL;
  args_info->data_type_orig = NULL;
  args_info->system_arg = NULL;
  args_info->system_orig = NULL;
  args_info->dim_x_orig = NULL;
  args_info->dim_y_orig = NULL;
  args_info->dim_z_orig = NULL;
  args_info->dim_t_orig = NULL;
  args_info->fac_x_orig = NULL;
  args_info->fac_y_orig = NULL;
  args_info->fac_z_orig = NULL;
  args_info->fac_t_orig = NULL;
  args_info->org_x_orig = NULL;
  args_info->org_y_orig = NULL;
  args_info->org_z_orig = NULL;
  args_info->org_t_orig = NULL;
  args_info->inc_x_orig = NULL;
  args_info->inc_y_orig = NULL;
  args_info->inc_z_orig = NULL;
  args_info->inc_t_orig = NULL;
  args_info->data_factor_orig = NULL;
  args_info->data_zero_orig = NULL;
  args_info->author_arg = NULL;
  args_info->author_orig = NULL;
  args_info->units_arg = NULL;
  args_info->units_orig = NULL;
  args_info->x_units_arg = NULL;
  args_info->x_units_orig = NULL;
  args_info->y_units_arg = NULL;
  args_info->y_units_orig = NULL;
  args_info->z_units_arg = NULL;
  args_info->z_units_orig = NULL;
  args_info->t_units_arg = NULL;
  args_info->t_units_orig = NULL;
  args_info->transparent_arg = NULL;
  args_info->transparent_orig = NULL;
  args_info->comment_arg = NULL;
  args_info->comment_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  args_info->frankenstein_arg = NULL;
  args_info->frankenstein_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->x_help = gengetopt_args_info_help[2] ;
  args_info->y_help = gengetopt_args_info_help[3] ;
  args_info->z_help = gengetopt_args_info_help[4] ;
  args_info->t_help = gengetopt_args_info_help[5] ;
  args_info->data_type_help = gengetopt_args_info_help[6] ;
  args_info->system_help = gengetopt_args_info_help[7] ;
  args_info->dim_x_help = gengetopt_args_info_help[8] ;
  args_info->dim_y_help = gengetopt_args_info_help[9] ;
  args_info->dim_z_help = gengetopt_args_info_help[10] ;
  args_info->dim_t_help = gengetopt_args_info_help[11] ;
  args_info->fac_x_help = gengetopt_args_info_help[12] ;
  args_info->fac_y_help = gengetopt_args_info_help[13] ;
  args_info->fac_z_help = gengetopt_args_info_help[14] ;
  args_info->fac_t_help = gengetopt_args_info_help[15] ;
  args_info->org_x_help = gengetopt_args_info_help[16] ;
  args_info->org_y_help = gengetopt_args_info_help[17] ;
  args_info->org_z_help = gengetopt_args_info_help[18] ;
  args_info->org_t_help = gengetopt_args_info_help[19] ;
  args_info->inc_x_help = gengetopt_args_info_help[20] ;
  args_info->inc_y_help = gengetopt_args_info_help[21] ;
  args_info->inc_z_help = gengetopt_args_info_help[22] ;
  args_info->inc_t_help = gengetopt_args_info_help[23] ;
  args_info->data_factor_help = gengetopt_args_info_help[24] ;
  args_info->data_zero_help = gengetopt_args_info_help[25] ;
  args_info->author_help = gengetopt_args_info_help[26] ;
  args_info->units_help = gengetopt_args_info_help[27] ;
  args_info->x_units_help = gengetopt_args_info_help[28] ;
  args_info->y_units_help = gengetopt_args_info_help[29] ;
  args_info->z_units_help = gengetopt_args_info_help[30] ;
  args_info->t_units_help = gengetopt_args_info_help[31] ;
  args_info->jive_time_help = gengetopt_args_info_help[32] ;
  args_info->transparent_help = gengetopt_args_info_help[33] ;
  args_info->no_transparent_help = gengetopt_args_info_help[34] ;
  args_info->decapitate_help = gengetopt_args_info_help[35] ;
  args_info->comment_help = gengetopt_args_info_help[36] ;
  args_info->clear_comment_help = gengetopt_args_info_help[37] ;
  args_info->output_file_help = gengetopt_args_info_help[38] ;
  args_info->frankenstein_help = gengetopt_args_info_help[39] ;
  args_info->explode_help = gengetopt_args_info_help[40] ;
  args_info->memfeminize_help = gengetopt_args_info_help[41] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->x_orig));
  free_string_field (&(args_info->y_orig));
  free_string_field (&(args_info->z_orig));
  free_string_field (&(args_info->t_orig));
  free_string_field (&(args_info->data_type_arg));
  free_string_field (&(args_info->data_type_orig));
  free_string_field (&(args_info->system_arg));
  free_string_field (&(args_info->system_orig));
  free_string_field (&(args_info->dim_x_orig));
  free_string_field (&(args_info->dim_y_orig));
  free_string_field (&(args_info->dim_z_orig));
  free_string_field (&(args_info->dim_t_orig));
  free_string_field (&(args_info->fac_x_orig));
  free_string_field (&(args_info->fac_y_orig));
  free_string_field (&(args_info->fac_z_orig));
  free_string_field (&(args_info->fac_t_orig));
  free_string_field (&(args_info->org_x_orig));
  free_string_field (&(args_info->org_y_orig));
  free_string_field (&(args_info->org_z_orig));
  free_string_field (&(args_info->org_t_orig));
  free_string_field (&(args_info->inc_x_orig));
  free_string_field (&(args_info->inc_y_orig));
  free_string_field (&(args_info->inc_z_orig));
  free_string_field (&(args_info->inc_t_orig));
  free_string_field (&(args_info->data_factor_orig));
  free_string_field (&(args_info->data_zero_orig));
  free_string_field (&(args_info->author_arg));
  free_string_field (&(args_info->author_orig));
  free_string_field (&(args_info->units_arg));
  free_string_field (&(args_info->units_orig));
  free_string_field (&(args_info->x_units_arg));
  free_string_field (&(args_info->x_units_orig));
  free_string_field (&(args_info->y_units_arg));
  free_string_field (&(args_info->y_units_orig));
  free_string_field (&(args_info->z_units_arg));
  free_string_field (&(args_info->z_units_orig));
  free_string_field (&(args_info->t_units_arg));
  free_string_field (&(args_info->t_units_orig));
  free_string_field (&(args_info->transparent_arg));
  free_string_field (&(args_info->transparent_orig));
  free_string_field (&(args_info->comment_arg));
  free_string_field (&(args_info->comment_orig));
  free_string_field (&(args_info->output_file_arg));
  free_string_field (&(args_info->output_file_orig));
  free_string_field (&(args_info->frankenstein_arg));
  free_string_field (&(args_info->frankenstein_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->x_given)
    write_into_file(outfile, "x", args_info->x_orig, 0);
  if (args_info->y_given)
    write_into_file(outfile, "y", args_info->y_orig, 0);
  if (args_info->z_given)
    write_into_file(outfile, "z", args_info->z_orig, 0);
  if (args_info->t_given)
    write_into_file(outfile, "t", args_info->t_orig, 0);
  if (args_info->data_type_given)
    write_into_file(outfile, "data-type", args_info->data_type_orig, 0);
  if (args_info->system_given)
    write_into_file(outfile, "system", args_info->system_orig, 0);
  if (args_info->dim_x_given)
    write_into_file(outfile, "dim-x", args_info->dim_x_orig, 0);
  if (args_info->dim_y_given)
    write_into_file(outfile, "dim-y", args_info->dim_y_orig, 0);
  if (args_info->dim_z_given)
    write_into_file(outfile, "dim-z", args_info->dim_z_orig, 0);
  if (args_info->dim_t_given)
    write_into_file(outfile, "dim-t", args_info->dim_t_orig, 0);
  if (args_info->fac_x_given)
    write_into_file(outfile, "fac-x", args_info->fac_x_orig, 0);
  if (args_info->fac_y_given)
    write_into_file(outfile, "fac-y", args_info->fac_y_orig, 0);
  if (args_info->fac_z_given)
    write_into_file(outfile, "fac-z", args_info->fac_z_orig, 0);
  if (args_info->fac_t_given)
    write_into_file(outfile, "fac-t", args_info->fac_t_orig, 0);
  if (args_info->org_x_given)
    write_into_file(outfile, "org-x", args_info->org_x_orig, 0);
  if (args_info->org_y_given)
    write_into_file(outfile, "org-y", args_info->org_y_orig, 0);
  if (args_info->org_z_given)
    write_into_file(outfile, "org-z", args_info->org_z_orig, 0);
  if (args_info->org_t_given)
    write_into_file(outfile, "org-t", args_info->org_t_orig, 0);
  if (args_info->inc_x_given)
    write_into_file(outfile, "inc-x", args_info->inc_x_orig, 0);
  if (args_info->inc_y_given)
    write_into_file(outfile, "inc-y", args_info->inc_y_orig, 0);
  if (args_info->inc_z_given)
    write_into_file(outfile, "inc-z", args_info->inc_z_orig, 0);
  if (args_info->inc_t_given)
    write_into_file(outfile, "inc-t", args_info->inc_t_orig, 0);
  if (args_info->data_factor_given)
    write_into_file(outfile, "data-factor", args_info->data_factor_orig, 0);
  if (args_info->data_zero_given)
    write_into_file(outfile, "data-zero", args_info->data_zero_orig, 0);
  if (args_info->author_given)
    write_into_file(outfile, "author", args_info->author_orig, 0);
  if (args_info->units_given)
    write_into_file(outfile, "units", args_info->units_orig, 0);
  if (args_info->x_units_given)
    write_into_file(outfile, "x-units", args_info->x_units_orig, 0);
  if (args_info->y_units_given)
    write_into_file(outfile, "y-units", args_info->y_units_orig, 0);
  if (args_info->z_units_given)
    write_into_file(outfile, "z-units", args_info->z_units_orig, 0);
  if (args_info->t_units_given)
    write_into_file(outfile, "t-units", args_info->t_units_orig, 0);
  if (args_info->jive_time_given)
    write_into_file(outfile, "jive-time", 0, 0 );
  if (args_info->transparent_given)
    write_into_file(outfile, "transparent", args_info->transparent_orig, 0);
  if (args_info->no_transparent_given)
    write_into_file(outfile, "no-transparent", 0, 0 );
  if (args_info->decapitate_given)
    write_into_file(outfile, "decapitate", 0, 0 );
  if (args_info->comment_given)
    write_into_file(outfile, "comment", args_info->comment_orig, 0);
  if (args_info->clear_comment_given)
    write_into_file(outfile, "clear-comment", 0, 0 );
  if (args_info->output_file_given)
    write_into_file(outfile, "output-file", args_info->output_file_orig, 0);
  if (args_info->frankenstein_given)
    write_into_file(outfile, "frankenstein", args_info->frankenstein_orig, 0);
  if (args_info->explode_given)
    write_into_file(outfile, "explode", 0, 0 );
  if (args_info->memfeminize_given)
    write_into_file(outfile, "memfeminize", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "x",	1, NULL, 'x' },
        { "y",	1, NULL, 'y' },
        { "z",	1, NULL, 'z' },
        { "t",	1, NULL, 't' },
        { "data-type",	1, NULL, 'd' },
        { "system",	1, NULL, 's' },
        { "dim-x",	1, NULL, 'X' },
        { "dim-y",	1, NULL, 'Y' },
        { "dim-z",	1, NULL, 'Z' },
        { "dim-t",	1, NULL, 'T' },
        { "fac-x",	1, NULL, '5' },
        { "fac-y",	1, NULL, '6' },
        { "fac-z",	1, NULL, '7' },
        { "fac-t",	1, NULL, '8' },
        { "org-x",	1, NULL, 'o' },
        { "org-y",	1, NULL, 'p' },
        { "org-z",	1, NULL, 'q' },
        { "org-t",	1, NULL, 'r' },
        { "inc-x",	1, NULL, 'I' },
        { "inc-y",	1, NULL, 'J' },
        { "inc-z",	1, NULL, 'K' },
        { "inc-t",	1, NULL, 'L' },
        { "data-factor",	1, NULL, 'S' },
        { "data-zero",	1, NULL, '0' },
        { "author",	1, NULL, 'A' },
        { "units",	1, NULL, 'u' },
        { "x-units",	1, NULL, '1' },
        { "y-units",	1, NULL, '2' },
        { "z-units",	1, NULL, '3' },
        { "t-units",	1, NULL, '4' },
        { "jive-time",	0, NULL, 'j' },
        { "transparent",	1, NULL, 'e' },
        { "no-transparent",	0, NULL, 'E' },
        { "decapitate",	0, NULL, 'D' },
        { "comment",	1, NULL, 'c' },
        { "clear-comment",	0, NULL, 'C' },
        { "output-file",	1, NULL, 'f' },
        { "frankenstein",	1, NULL, 'F' },
        { "explode",	0, NULL, 'l' },
        { "memfeminize",	0, NULL, 'm' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVx:y:z:t:d:s:X:Y:Z:T:5:6:7:8:o:p:q:r:I:J:K:L:S:0:A:u:1:2:3:4:je:EDc:Cf:F:lm", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'x':	/* number of x pixels.  */
        
        
          if (update_arg( (void *)&(args_info->x_arg), 
               &(args_info->x_orig), &(args_info->x_given),
              &(local_args_info.x_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "x", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'y':	/* number of y pixels.  */
        
        
          if (update_arg( (void *)&(args_info->y_arg), 
               &(args_info->y_orig), &(args_info->y_given),
              &(local_args_info.y_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "y", 'y',
              additional_error))
            goto failure;
        
          break;
        case 'z':	/* number of z pixels.  */
        
        
          if (update_arg( (void *)&(args_info->z_arg), 
               &(args_info->z_orig), &(args_info->z_given),
              &(local_args_info.z_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "z", 'z',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* number of time slices.  */
        
        
          if (update_arg( (void *)&(args_info->t_arg), 
               &(args_info->t_orig), &(args_info->t_given),
              &(local_args_info.t_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "t", 't',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* char byte int uint float long double vec3f vec4f vec3d vec4d OR rgba.  */
        
        
          if (update_arg( (void *)&(args_info->data_type_arg), 
               &(args_info->data_type_orig), &(args_info->data_type_given),
              &(local_args_info.data_type_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "data-type", 'd',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* big_||little_endian.  */
        
        
          if (update_arg( (void *)&(args_info->system_arg), 
               &(args_info->system_orig), &(args_info->system_given),
              &(local_args_info.system_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "system", 's',
              additional_error))
            goto failure;
        
          break;
        case 'X':	/* Size in x.  */
        
        
          if (update_arg( (void *)&(args_info->dim_x_arg), 
               &(args_info->dim_x_orig), &(args_info->dim_x_given),
              &(local_args_info.dim_x_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "dim-x", 'X',
              additional_error))
            goto failure;
        
          break;
        case 'Y':	/* Size in y.  */
        
        
          if (update_arg( (void *)&(args_info->dim_y_arg), 
               &(args_info->dim_y_orig), &(args_info->dim_y_given),
              &(local_args_info.dim_y_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "dim-y", 'Y',
              additional_error))
            goto failure;
        
          break;
        case 'Z':	/* Size in z.  */
        
        
          if (update_arg( (void *)&(args_info->dim_z_arg), 
               &(args_info->dim_z_orig), &(args_info->dim_z_given),
              &(local_args_info.dim_z_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "dim-z", 'Z',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Duration.  */
        
        
          if (update_arg( (void *)&(args_info->dim_t_arg), 
               &(args_info->dim_t_orig), &(args_info->dim_t_given),
              &(local_args_info.dim_t_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "dim-t", 'T',
              additional_error))
            goto failure;
        
          break;
        case '5':	/* Scaling factor in x.  */
        
        
          if (update_arg( (void *)&(args_info->fac_x_arg), 
               &(args_info->fac_x_orig), &(args_info->fac_x_given),
              &(local_args_info.fac_x_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fac-x", '5',
              additional_error))
            goto failure;
        
          break;
        case '6':	/* Scaling factor in y.  */
        
        
          if (update_arg( (void *)&(args_info->fac_y_arg), 
               &(args_info->fac_y_orig), &(args_info->fac_y_given),
              &(local_args_info.fac_y_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fac-y", '6',
              additional_error))
            goto failure;
        
          break;
        case '7':	/* Scaling factor in z.  */
        
        
          if (update_arg( (void *)&(args_info->fac_z_arg), 
               &(args_info->fac_z_orig), &(args_info->fac_z_given),
              &(local_args_info.fac_z_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fac-z", '7',
              additional_error))
            goto failure;
        
          break;
        case '8':	/* Scaling factor in t.  */
        
        
          if (update_arg( (void *)&(args_info->fac_t_arg), 
               &(args_info->fac_t_orig), &(args_info->fac_t_given),
              &(local_args_info.fac_t_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fac-t", '8',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Origin for x.  */
        
        
          if (update_arg( (void *)&(args_info->org_x_arg), 
               &(args_info->org_x_orig), &(args_info->org_x_given),
              &(local_args_info.org_x_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "org-x", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Origin for y.  */
        
        
          if (update_arg( (void *)&(args_info->org_y_arg), 
               &(args_info->org_y_orig), &(args_info->org_y_given),
              &(local_args_info.org_y_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "org-y", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Origin for z.  */
        
        
          if (update_arg( (void *)&(args_info->org_z_arg), 
               &(args_info->org_z_orig), &(args_info->org_z_given),
              &(local_args_info.org_z_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "org-z", 'q',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Origin for t.  */
        
        
          if (update_arg( (void *)&(args_info->org_t_arg), 
               &(args_info->org_t_orig), &(args_info->org_t_given),
              &(local_args_info.org_t_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "org-t", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'I':	/* Increment in x.  */
        
        
          if (update_arg( (void *)&(args_info->inc_x_arg), 
               &(args_info->inc_x_orig), &(args_info->inc_x_given),
              &(local_args_info.inc_x_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "inc-x", 'I',
              additional_error))
            goto failure;
        
          break;
        case 'J':	/* Increment in y.  */
        
        
          if (update_arg( (void *)&(args_info->inc_y_arg), 
               &(args_info->inc_y_orig), &(args_info->inc_y_given),
              &(local_args_info.inc_y_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "inc-y", 'J',
              additional_error))
            goto failure;
        
          break;
        case 'K':	/* Increment in z.  */
        
        
          if (update_arg( (void *)&(args_info->inc_z_arg), 
               &(args_info->inc_z_orig), &(args_info->inc_z_given),
              &(local_args_info.inc_z_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "inc-z", 'K',
              additional_error))
            goto failure;
        
          break;
        case 'L':	/* Increment in t.  */
        
        
          if (update_arg( (void *)&(args_info->inc_t_arg), 
               &(args_info->inc_t_orig), &(args_info->inc_t_given),
              &(local_args_info.inc_t_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "inc-t", 'L',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Scaling factor for data.  */
        
        
          if (update_arg( (void *)&(args_info->data_factor_arg), 
               &(args_info->data_factor_orig), &(args_info->data_factor_given),
              &(local_args_info.data_factor_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "data-factor", 'S',
              additional_error))
            goto failure;
        
          break;
        case '0':	/* Origin for data scaling.  */
        
        
          if (update_arg( (void *)&(args_info->data_zero_arg), 
               &(args_info->data_zero_orig), &(args_info->data_zero_given),
              &(local_args_info.data_zero_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "data-zero", '0',
              additional_error))
            goto failure;
        
          break;
        case 'A':	/* Author name with no spaces.  */
        
        
          if (update_arg( (void *)&(args_info->author_arg), 
               &(args_info->author_orig), &(args_info->author_given),
              &(local_args_info.author_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "author", 'A',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* Data units.  */
        
        
          if (update_arg( (void *)&(args_info->units_arg), 
               &(args_info->units_orig), &(args_info->units_given),
              &(local_args_info.units_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "units", 'u',
              additional_error))
            goto failure;
        
          break;
        case '1':	/* Units for x.  */
        
        
          if (update_arg( (void *)&(args_info->x_units_arg), 
               &(args_info->x_units_orig), &(args_info->x_units_given),
              &(local_args_info.x_units_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "x-units", '1',
              additional_error))
            goto failure;
        
          break;
        case '2':	/* Units for y.  */
        
        
          if (update_arg( (void *)&(args_info->y_units_arg), 
               &(args_info->y_units_orig), &(args_info->y_units_given),
              &(local_args_info.y_units_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "y-units", '2',
              additional_error))
            goto failure;
        
          break;
        case '3':	/* Units for z.  */
        
        
          if (update_arg( (void *)&(args_info->z_units_arg), 
               &(args_info->z_units_orig), &(args_info->z_units_given),
              &(local_args_info.z_units_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "z-units", '3',
              additional_error))
            goto failure;
        
          break;
        case '4':	/* Units for t.  */
        
        
          if (update_arg( (void *)&(args_info->t_units_arg), 
               &(args_info->t_units_orig), &(args_info->t_units_given),
              &(local_args_info.t_units_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "t-units", '4',
              additional_error))
            goto failure;
        
          break;
        case 'j':	/* Make no. time slices jive with data size.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->jive_time_given),
              &(local_args_info.jive_time_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "jive-time", 'j',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* Transparent pixel value in hex.  */
        
        
          if (update_arg( (void *)&(args_info->transparent_arg), 
               &(args_info->transparent_orig), &(args_info->transparent_given),
              &(local_args_info.transparent_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "transparent", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'E':	/* Turn transparency off.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->no_transparent_given),
              &(local_args_info.no_transparent_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "no-transparent", 'E',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* Remove header.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->decapitate_given),
              &(local_args_info.decapitate_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "decapitate", 'D',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Add a line of comment.  */
        
        
          if (update_arg( (void *)&(args_info->comment_arg), 
               &(args_info->comment_orig), &(args_info->comment_given),
              &(local_args_info.comment_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "comment", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* Clear all comments.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->clear_comment_given),
              &(local_args_info.clear_comment_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "clear-comment", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* output file.  */
        
        
          if (update_arg( (void *)&(args_info->output_file_arg), 
               &(args_info->output_file_orig), &(args_info->output_file_given),
              &(local_args_info.output_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output-file", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'F':	/* attach header to this file.  */
        
        
          if (update_arg( (void *)&(args_info->frankenstein_arg), 
               &(args_info->frankenstein_orig), &(args_info->frankenstein_given),
              &(local_args_info.frankenstein_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "frankenstein", 'F',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* explode file into igb time slices.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->explode_given),
              &(local_args_info.explode_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "explode", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* convert igb to memfem format.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->memfeminize_given),
              &(local_args_info.memfeminize_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "memfeminize", 'm',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
