/*
  File autogenerated by gengetopt version 2.21
  generated with the following command:
  gengetopt -u 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: igbhead [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                 Print help and exit",
  "  -V, --version              Print version and exit",
  "  -x, --x=INT                number of x pixels",
  "  -y, --y=INT                number of y pixels",
  "  -z, --z=INT                number of z pixels",
  "  -t, --t=INT                number of time slices",
  "  -d, --data-type=STRING     char byte int uint float long double vec3f vec4f \n                               vec3d vec4d OR rgba",
  "  -s, --system=STRING        big_||little_endian",
  "  -X, --dim-x=FLOAT          Size in x",
  "  -Y, --dim-y=FLOAT          Size in y",
  "  -Z, --dim-z=FLOAT          Size in z",
  "  -T, --dim-t=FLOAT          Duration",
  "  -5, --fac-x=FLOAT          Scaling factor in x",
  "  -6, --fac-y=FLOAT          Scaling factor in y",
  "  -7, --fac-z=FLOAT          Scaling factor in z",
  "  -8, --fac-t=FLOAT          Scaling factor in t",
  "  -o, --org-x=FLOAT          Origin for x",
  "  -p, --org-y=FLOAT          Origin for y",
  "  -q, --org-z=FLOAT          Origin for z",
  "  -r, --org-t=FLOAT          Origin for t",
  "  -I, --inc-x=FLOAT          Increment in x",
  "  -J, --inc-y=FLOAT          Increment in y",
  "  -K, --inc-z=FLOAT          Increment in z",
  "  -L, --inc-t=FLOAT          Increment in t",
  "  -S, --data-factor=FLOAT    Scaling factor for data",
  "  -0, --data-zero=FLOAT      Origin for data scaling",
  "  -A, --author=STRING        Author name with no spaces",
  "  -1, --x-units=STRING       Units for x",
  "  -2, --y-units=STRING       Units for y",
  "  -3, --z-units=STRING       Units for z",
  "  -4, --t-units=STRING       Units for t",
  "  -j, --jive-time            Make no. time slices jive with data size",
  "  -e, --transparent=STRING   Transparent pixel value in hex",
  "  -E, --no-transparent       Turn transparency off",
  "  -D, --decapitate           Remove header",
  "  -c, --comment=STRING       Add a line of comment",
  "  -C, --clear-comment        Clear all comments",
  "  -f, --output-file=STRING   output file",
  "  -F, --frankenstein=STRING  attach header to this file",
  "  -l, --explode              explode file into igb time slices",
  "  -m, --memfeminize          convert igb to memfem format",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->x_given = 0 ;
  args_info->y_given = 0 ;
  args_info->z_given = 0 ;
  args_info->t_given = 0 ;
  args_info->data_type_given = 0 ;
  args_info->system_given = 0 ;
  args_info->dim_x_given = 0 ;
  args_info->dim_y_given = 0 ;
  args_info->dim_z_given = 0 ;
  args_info->dim_t_given = 0 ;
  args_info->fac_x_given = 0 ;
  args_info->fac_y_given = 0 ;
  args_info->fac_z_given = 0 ;
  args_info->fac_t_given = 0 ;
  args_info->org_x_given = 0 ;
  args_info->org_y_given = 0 ;
  args_info->org_z_given = 0 ;
  args_info->org_t_given = 0 ;
  args_info->inc_x_given = 0 ;
  args_info->inc_y_given = 0 ;
  args_info->inc_z_given = 0 ;
  args_info->inc_t_given = 0 ;
  args_info->data_factor_given = 0 ;
  args_info->data_zero_given = 0 ;
  args_info->author_given = 0 ;
  args_info->x_units_given = 0 ;
  args_info->y_units_given = 0 ;
  args_info->z_units_given = 0 ;
  args_info->t_units_given = 0 ;
  args_info->jive_time_given = 0 ;
  args_info->transparent_given = 0 ;
  args_info->no_transparent_given = 0 ;
  args_info->decapitate_given = 0 ;
  args_info->comment_given = 0 ;
  args_info->clear_comment_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->frankenstein_given = 0 ;
  args_info->explode_given = 0 ;
  args_info->memfeminize_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->x_orig = NULL;
  args_info->y_orig = NULL;
  args_info->z_orig = NULL;
  args_info->t_orig = NULL;
  args_info->data_type_arg = NULL;
  args_info->data_type_orig = NULL;
  args_info->system_arg = NULL;
  args_info->system_orig = NULL;
  args_info->dim_x_orig = NULL;
  args_info->dim_y_orig = NULL;
  args_info->dim_z_orig = NULL;
  args_info->dim_t_orig = NULL;
  args_info->fac_x_orig = NULL;
  args_info->fac_y_orig = NULL;
  args_info->fac_z_orig = NULL;
  args_info->fac_t_orig = NULL;
  args_info->org_x_orig = NULL;
  args_info->org_y_orig = NULL;
  args_info->org_z_orig = NULL;
  args_info->org_t_orig = NULL;
  args_info->inc_x_orig = NULL;
  args_info->inc_y_orig = NULL;
  args_info->inc_z_orig = NULL;
  args_info->inc_t_orig = NULL;
  args_info->data_factor_orig = NULL;
  args_info->data_zero_orig = NULL;
  args_info->author_arg = NULL;
  args_info->author_orig = NULL;
  args_info->x_units_arg = NULL;
  args_info->x_units_orig = NULL;
  args_info->y_units_arg = NULL;
  args_info->y_units_orig = NULL;
  args_info->z_units_arg = NULL;
  args_info->z_units_orig = NULL;
  args_info->t_units_arg = NULL;
  args_info->t_units_orig = NULL;
  args_info->transparent_arg = NULL;
  args_info->transparent_orig = NULL;
  args_info->comment_arg = NULL;
  args_info->comment_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  args_info->frankenstein_arg = NULL;
  args_info->frankenstein_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->x_help = gengetopt_args_info_help[2] ;
  args_info->y_help = gengetopt_args_info_help[3] ;
  args_info->z_help = gengetopt_args_info_help[4] ;
  args_info->t_help = gengetopt_args_info_help[5] ;
  args_info->data_type_help = gengetopt_args_info_help[6] ;
  args_info->system_help = gengetopt_args_info_help[7] ;
  args_info->dim_x_help = gengetopt_args_info_help[8] ;
  args_info->dim_y_help = gengetopt_args_info_help[9] ;
  args_info->dim_z_help = gengetopt_args_info_help[10] ;
  args_info->dim_t_help = gengetopt_args_info_help[11] ;
  args_info->fac_x_help = gengetopt_args_info_help[12] ;
  args_info->fac_y_help = gengetopt_args_info_help[13] ;
  args_info->fac_z_help = gengetopt_args_info_help[14] ;
  args_info->fac_t_help = gengetopt_args_info_help[15] ;
  args_info->org_x_help = gengetopt_args_info_help[16] ;
  args_info->org_y_help = gengetopt_args_info_help[17] ;
  args_info->org_z_help = gengetopt_args_info_help[18] ;
  args_info->org_t_help = gengetopt_args_info_help[19] ;
  args_info->inc_x_help = gengetopt_args_info_help[20] ;
  args_info->inc_y_help = gengetopt_args_info_help[21] ;
  args_info->inc_z_help = gengetopt_args_info_help[22] ;
  args_info->inc_t_help = gengetopt_args_info_help[23] ;
  args_info->data_factor_help = gengetopt_args_info_help[24] ;
  args_info->data_zero_help = gengetopt_args_info_help[25] ;
  args_info->author_help = gengetopt_args_info_help[26] ;
  args_info->x_units_help = gengetopt_args_info_help[27] ;
  args_info->y_units_help = gengetopt_args_info_help[28] ;
  args_info->z_units_help = gengetopt_args_info_help[29] ;
  args_info->t_units_help = gengetopt_args_info_help[30] ;
  args_info->jive_time_help = gengetopt_args_info_help[31] ;
  args_info->transparent_help = gengetopt_args_info_help[32] ;
  args_info->no_transparent_help = gengetopt_args_info_help[33] ;
  args_info->decapitate_help = gengetopt_args_info_help[34] ;
  args_info->comment_help = gengetopt_args_info_help[35] ;
  args_info->clear_comment_help = gengetopt_args_info_help[36] ;
  args_info->output_file_help = gengetopt_args_info_help[37] ;
  args_info->frankenstein_help = gengetopt_args_info_help[38] ;
  args_info->explode_help = gengetopt_args_info_help[39] ;
  args_info->memfeminize_help = gengetopt_args_info_help[40] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

struct cmdline_parser_params *
cmdline_parser_params_init()
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));

  if (params)
    { 
      params->override = 0;
      params->initialize = 0;
      params->check_required = 0;
      params->check_ambiguity = 0;
    }
    
  return params;
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->x_orig)
    {
      free (args_info->x_orig); /* free previous argument */
      args_info->x_orig = 0;
    }
  if (args_info->y_orig)
    {
      free (args_info->y_orig); /* free previous argument */
      args_info->y_orig = 0;
    }
  if (args_info->z_orig)
    {
      free (args_info->z_orig); /* free previous argument */
      args_info->z_orig = 0;
    }
  if (args_info->t_orig)
    {
      free (args_info->t_orig); /* free previous argument */
      args_info->t_orig = 0;
    }
  if (args_info->data_type_arg)
    {
      free (args_info->data_type_arg); /* free previous argument */
      args_info->data_type_arg = 0;
    }
  if (args_info->data_type_orig)
    {
      free (args_info->data_type_orig); /* free previous argument */
      args_info->data_type_orig = 0;
    }
  if (args_info->system_arg)
    {
      free (args_info->system_arg); /* free previous argument */
      args_info->system_arg = 0;
    }
  if (args_info->system_orig)
    {
      free (args_info->system_orig); /* free previous argument */
      args_info->system_orig = 0;
    }
  if (args_info->dim_x_orig)
    {
      free (args_info->dim_x_orig); /* free previous argument */
      args_info->dim_x_orig = 0;
    }
  if (args_info->dim_y_orig)
    {
      free (args_info->dim_y_orig); /* free previous argument */
      args_info->dim_y_orig = 0;
    }
  if (args_info->dim_z_orig)
    {
      free (args_info->dim_z_orig); /* free previous argument */
      args_info->dim_z_orig = 0;
    }
  if (args_info->dim_t_orig)
    {
      free (args_info->dim_t_orig); /* free previous argument */
      args_info->dim_t_orig = 0;
    }
  if (args_info->fac_x_orig)
    {
      free (args_info->fac_x_orig); /* free previous argument */
      args_info->fac_x_orig = 0;
    }
  if (args_info->fac_y_orig)
    {
      free (args_info->fac_y_orig); /* free previous argument */
      args_info->fac_y_orig = 0;
    }
  if (args_info->fac_z_orig)
    {
      free (args_info->fac_z_orig); /* free previous argument */
      args_info->fac_z_orig = 0;
    }
  if (args_info->fac_t_orig)
    {
      free (args_info->fac_t_orig); /* free previous argument */
      args_info->fac_t_orig = 0;
    }
  if (args_info->org_x_orig)
    {
      free (args_info->org_x_orig); /* free previous argument */
      args_info->org_x_orig = 0;
    }
  if (args_info->org_y_orig)
    {
      free (args_info->org_y_orig); /* free previous argument */
      args_info->org_y_orig = 0;
    }
  if (args_info->org_z_orig)
    {
      free (args_info->org_z_orig); /* free previous argument */
      args_info->org_z_orig = 0;
    }
  if (args_info->org_t_orig)
    {
      free (args_info->org_t_orig); /* free previous argument */
      args_info->org_t_orig = 0;
    }
  if (args_info->inc_x_orig)
    {
      free (args_info->inc_x_orig); /* free previous argument */
      args_info->inc_x_orig = 0;
    }
  if (args_info->inc_y_orig)
    {
      free (args_info->inc_y_orig); /* free previous argument */
      args_info->inc_y_orig = 0;
    }
  if (args_info->inc_z_orig)
    {
      free (args_info->inc_z_orig); /* free previous argument */
      args_info->inc_z_orig = 0;
    }
  if (args_info->inc_t_orig)
    {
      free (args_info->inc_t_orig); /* free previous argument */
      args_info->inc_t_orig = 0;
    }
  if (args_info->data_factor_orig)
    {
      free (args_info->data_factor_orig); /* free previous argument */
      args_info->data_factor_orig = 0;
    }
  if (args_info->data_zero_orig)
    {
      free (args_info->data_zero_orig); /* free previous argument */
      args_info->data_zero_orig = 0;
    }
  if (args_info->author_arg)
    {
      free (args_info->author_arg); /* free previous argument */
      args_info->author_arg = 0;
    }
  if (args_info->author_orig)
    {
      free (args_info->author_orig); /* free previous argument */
      args_info->author_orig = 0;
    }
  if (args_info->x_units_arg)
    {
      free (args_info->x_units_arg); /* free previous argument */
      args_info->x_units_arg = 0;
    }
  if (args_info->x_units_orig)
    {
      free (args_info->x_units_orig); /* free previous argument */
      args_info->x_units_orig = 0;
    }
  if (args_info->y_units_arg)
    {
      free (args_info->y_units_arg); /* free previous argument */
      args_info->y_units_arg = 0;
    }
  if (args_info->y_units_orig)
    {
      free (args_info->y_units_orig); /* free previous argument */
      args_info->y_units_orig = 0;
    }
  if (args_info->z_units_arg)
    {
      free (args_info->z_units_arg); /* free previous argument */
      args_info->z_units_arg = 0;
    }
  if (args_info->z_units_orig)
    {
      free (args_info->z_units_orig); /* free previous argument */
      args_info->z_units_orig = 0;
    }
  if (args_info->t_units_arg)
    {
      free (args_info->t_units_arg); /* free previous argument */
      args_info->t_units_arg = 0;
    }
  if (args_info->t_units_orig)
    {
      free (args_info->t_units_orig); /* free previous argument */
      args_info->t_units_orig = 0;
    }
  if (args_info->transparent_arg)
    {
      free (args_info->transparent_arg); /* free previous argument */
      args_info->transparent_arg = 0;
    }
  if (args_info->transparent_orig)
    {
      free (args_info->transparent_orig); /* free previous argument */
      args_info->transparent_orig = 0;
    }
  if (args_info->comment_arg)
    {
      free (args_info->comment_arg); /* free previous argument */
      args_info->comment_arg = 0;
    }
  if (args_info->comment_orig)
    {
      free (args_info->comment_orig); /* free previous argument */
      args_info->comment_orig = 0;
    }
  if (args_info->output_file_arg)
    {
      free (args_info->output_file_arg); /* free previous argument */
      args_info->output_file_arg = 0;
    }
  if (args_info->output_file_orig)
    {
      free (args_info->output_file_orig); /* free previous argument */
      args_info->output_file_orig = 0;
    }
  if (args_info->frankenstein_arg)
    {
      free (args_info->frankenstein_arg); /* free previous argument */
      args_info->frankenstein_arg = 0;
    }
  if (args_info->frankenstein_orig)
    {
      free (args_info->frankenstein_orig); /* free previous argument */
      args_info->frankenstein_orig = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->x_given) {
    if (args_info->x_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "x", args_info->x_orig);
    } else {
      fprintf(outfile, "%s\n", "x");
    }
  }
  if (args_info->y_given) {
    if (args_info->y_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "y", args_info->y_orig);
    } else {
      fprintf(outfile, "%s\n", "y");
    }
  }
  if (args_info->z_given) {
    if (args_info->z_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "z", args_info->z_orig);
    } else {
      fprintf(outfile, "%s\n", "z");
    }
  }
  if (args_info->t_given) {
    if (args_info->t_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "t", args_info->t_orig);
    } else {
      fprintf(outfile, "%s\n", "t");
    }
  }
  if (args_info->data_type_given) {
    if (args_info->data_type_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "data-type", args_info->data_type_orig);
    } else {
      fprintf(outfile, "%s\n", "data-type");
    }
  }
  if (args_info->system_given) {
    if (args_info->system_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "system", args_info->system_orig);
    } else {
      fprintf(outfile, "%s\n", "system");
    }
  }
  if (args_info->dim_x_given) {
    if (args_info->dim_x_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "dim-x", args_info->dim_x_orig);
    } else {
      fprintf(outfile, "%s\n", "dim-x");
    }
  }
  if (args_info->dim_y_given) {
    if (args_info->dim_y_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "dim-y", args_info->dim_y_orig);
    } else {
      fprintf(outfile, "%s\n", "dim-y");
    }
  }
  if (args_info->dim_z_given) {
    if (args_info->dim_z_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "dim-z", args_info->dim_z_orig);
    } else {
      fprintf(outfile, "%s\n", "dim-z");
    }
  }
  if (args_info->dim_t_given) {
    if (args_info->dim_t_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "dim-t", args_info->dim_t_orig);
    } else {
      fprintf(outfile, "%s\n", "dim-t");
    }
  }
  if (args_info->fac_x_given) {
    if (args_info->fac_x_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "fac-x", args_info->fac_x_orig);
    } else {
      fprintf(outfile, "%s\n", "fac-x");
    }
  }
  if (args_info->fac_y_given) {
    if (args_info->fac_y_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "fac-y", args_info->fac_y_orig);
    } else {
      fprintf(outfile, "%s\n", "fac-y");
    }
  }
  if (args_info->fac_z_given) {
    if (args_info->fac_z_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "fac-z", args_info->fac_z_orig);
    } else {
      fprintf(outfile, "%s\n", "fac-z");
    }
  }
  if (args_info->fac_t_given) {
    if (args_info->fac_t_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "fac-t", args_info->fac_t_orig);
    } else {
      fprintf(outfile, "%s\n", "fac-t");
    }
  }
  if (args_info->org_x_given) {
    if (args_info->org_x_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "org-x", args_info->org_x_orig);
    } else {
      fprintf(outfile, "%s\n", "org-x");
    }
  }
  if (args_info->org_y_given) {
    if (args_info->org_y_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "org-y", args_info->org_y_orig);
    } else {
      fprintf(outfile, "%s\n", "org-y");
    }
  }
  if (args_info->org_z_given) {
    if (args_info->org_z_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "org-z", args_info->org_z_orig);
    } else {
      fprintf(outfile, "%s\n", "org-z");
    }
  }
  if (args_info->org_t_given) {
    if (args_info->org_t_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "org-t", args_info->org_t_orig);
    } else {
      fprintf(outfile, "%s\n", "org-t");
    }
  }
  if (args_info->inc_x_given) {
    if (args_info->inc_x_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "inc-x", args_info->inc_x_orig);
    } else {
      fprintf(outfile, "%s\n", "inc-x");
    }
  }
  if (args_info->inc_y_given) {
    if (args_info->inc_y_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "inc-y", args_info->inc_y_orig);
    } else {
      fprintf(outfile, "%s\n", "inc-y");
    }
  }
  if (args_info->inc_z_given) {
    if (args_info->inc_z_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "inc-z", args_info->inc_z_orig);
    } else {
      fprintf(outfile, "%s\n", "inc-z");
    }
  }
  if (args_info->inc_t_given) {
    if (args_info->inc_t_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "inc-t", args_info->inc_t_orig);
    } else {
      fprintf(outfile, "%s\n", "inc-t");
    }
  }
  if (args_info->data_factor_given) {
    if (args_info->data_factor_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "data-factor", args_info->data_factor_orig);
    } else {
      fprintf(outfile, "%s\n", "data-factor");
    }
  }
  if (args_info->data_zero_given) {
    if (args_info->data_zero_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "data-zero", args_info->data_zero_orig);
    } else {
      fprintf(outfile, "%s\n", "data-zero");
    }
  }
  if (args_info->author_given) {
    if (args_info->author_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "author", args_info->author_orig);
    } else {
      fprintf(outfile, "%s\n", "author");
    }
  }
  if (args_info->x_units_given) {
    if (args_info->x_units_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "x-units", args_info->x_units_orig);
    } else {
      fprintf(outfile, "%s\n", "x-units");
    }
  }
  if (args_info->y_units_given) {
    if (args_info->y_units_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "y-units", args_info->y_units_orig);
    } else {
      fprintf(outfile, "%s\n", "y-units");
    }
  }
  if (args_info->z_units_given) {
    if (args_info->z_units_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "z-units", args_info->z_units_orig);
    } else {
      fprintf(outfile, "%s\n", "z-units");
    }
  }
  if (args_info->t_units_given) {
    if (args_info->t_units_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "t-units", args_info->t_units_orig);
    } else {
      fprintf(outfile, "%s\n", "t-units");
    }
  }
  if (args_info->jive_time_given) {
    fprintf(outfile, "%s\n", "jive-time");
  }
  if (args_info->transparent_given) {
    if (args_info->transparent_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "transparent", args_info->transparent_orig);
    } else {
      fprintf(outfile, "%s\n", "transparent");
    }
  }
  if (args_info->no_transparent_given) {
    fprintf(outfile, "%s\n", "no-transparent");
  }
  if (args_info->decapitate_given) {
    fprintf(outfile, "%s\n", "decapitate");
  }
  if (args_info->comment_given) {
    if (args_info->comment_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "comment", args_info->comment_orig);
    } else {
      fprintf(outfile, "%s\n", "comment");
    }
  }
  if (args_info->clear_comment_given) {
    fprintf(outfile, "%s\n", "clear-comment");
  }
  if (args_info->output_file_given) {
    if (args_info->output_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "output-file", args_info->output_file_orig);
    } else {
      fprintf(outfile, "%s\n", "output-file");
    }
  }
  if (args_info->frankenstein_given) {
    if (args_info->frankenstein_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "frankenstein", args_info->frankenstein_orig);
    } else {
      fprintf(outfile, "%s\n", "frankenstein");
    }
  }
  if (args_info->explode_given) {
    fprintf(outfile, "%s\n", "explode");
  }
  if (args_info->memfeminize_given) {
    fprintf(outfile, "%s\n", "memfeminize");
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "x",	1, NULL, 'x' },
        { "y",	1, NULL, 'y' },
        { "z",	1, NULL, 'z' },
        { "t",	1, NULL, 't' },
        { "data-type",	1, NULL, 'd' },
        { "system",	1, NULL, 's' },
        { "dim-x",	1, NULL, 'X' },
        { "dim-y",	1, NULL, 'Y' },
        { "dim-z",	1, NULL, 'Z' },
        { "dim-t",	1, NULL, 'T' },
        { "fac-x",	1, NULL, '5' },
        { "fac-y",	1, NULL, '6' },
        { "fac-z",	1, NULL, '7' },
        { "fac-t",	1, NULL, '8' },
        { "org-x",	1, NULL, 'o' },
        { "org-y",	1, NULL, 'p' },
        { "org-z",	1, NULL, 'q' },
        { "org-t",	1, NULL, 'r' },
        { "inc-x",	1, NULL, 'I' },
        { "inc-y",	1, NULL, 'J' },
        { "inc-z",	1, NULL, 'K' },
        { "inc-t",	1, NULL, 'L' },
        { "data-factor",	1, NULL, 'S' },
        { "data-zero",	1, NULL, '0' },
        { "author",	1, NULL, 'A' },
        { "x-units",	1, NULL, '1' },
        { "y-units",	1, NULL, '2' },
        { "z-units",	1, NULL, '3' },
        { "t-units",	1, NULL, '4' },
        { "jive-time",	0, NULL, 'j' },
        { "transparent",	1, NULL, 'e' },
        { "no-transparent",	0, NULL, 'E' },
        { "decapitate",	0, NULL, 'D' },
        { "comment",	1, NULL, 'c' },
        { "clear-comment",	0, NULL, 'C' },
        { "output-file",	1, NULL, 'f' },
        { "frankenstein",	1, NULL, 'F' },
        { "explode",	0, NULL, 'l' },
        { "memfeminize",	0, NULL, 'm' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVx:y:z:t:d:s:X:Y:Z:T:5:6:7:8:o:p:q:r:I:J:K:L:S:0:A:1:2:3:4:je:EDc:Cf:F:lm", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'x':	/* number of x pixels.  */
          if (local_args_info.x_given || (check_ambiguity && args_info->x_given))
            {
              fprintf (stderr, "%s: `--x' (`-x') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->x_given && ! override)
            continue;
          local_args_info.x_given = 1;
          args_info->x_given = 1;
          args_info->x_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->x_orig)
            free (args_info->x_orig); /* free previous string */
          args_info->x_orig = gengetopt_strdup (optarg);
          break;

        case 'y':	/* number of y pixels.  */
          if (local_args_info.y_given || (check_ambiguity && args_info->y_given))
            {
              fprintf (stderr, "%s: `--y' (`-y') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->y_given && ! override)
            continue;
          local_args_info.y_given = 1;
          args_info->y_given = 1;
          args_info->y_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->y_orig)
            free (args_info->y_orig); /* free previous string */
          args_info->y_orig = gengetopt_strdup (optarg);
          break;

        case 'z':	/* number of z pixels.  */
          if (local_args_info.z_given || (check_ambiguity && args_info->z_given))
            {
              fprintf (stderr, "%s: `--z' (`-z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->z_given && ! override)
            continue;
          local_args_info.z_given = 1;
          args_info->z_given = 1;
          args_info->z_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->z_orig)
            free (args_info->z_orig); /* free previous string */
          args_info->z_orig = gengetopt_strdup (optarg);
          break;

        case 't':	/* number of time slices.  */
          if (local_args_info.t_given || (check_ambiguity && args_info->t_given))
            {
              fprintf (stderr, "%s: `--t' (`-t') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->t_given && ! override)
            continue;
          local_args_info.t_given = 1;
          args_info->t_given = 1;
          args_info->t_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->t_orig)
            free (args_info->t_orig); /* free previous string */
          args_info->t_orig = gengetopt_strdup (optarg);
          break;

        case 'd':	/* char byte int uint float long double vec3f vec4f vec3d vec4d OR rgba.  */
          if (local_args_info.data_type_given || (check_ambiguity && args_info->data_type_given))
            {
              fprintf (stderr, "%s: `--data-type' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->data_type_given && ! override)
            continue;
          local_args_info.data_type_given = 1;
          args_info->data_type_given = 1;
          if (args_info->data_type_arg)
            free (args_info->data_type_arg); /* free previous string */
          args_info->data_type_arg = gengetopt_strdup (optarg);
          if (args_info->data_type_orig)
            free (args_info->data_type_orig); /* free previous string */
          args_info->data_type_orig = gengetopt_strdup (optarg);
          break;

        case 's':	/* big_||little_endian.  */
          if (local_args_info.system_given || (check_ambiguity && args_info->system_given))
            {
              fprintf (stderr, "%s: `--system' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->system_given && ! override)
            continue;
          local_args_info.system_given = 1;
          args_info->system_given = 1;
          if (args_info->system_arg)
            free (args_info->system_arg); /* free previous string */
          args_info->system_arg = gengetopt_strdup (optarg);
          if (args_info->system_orig)
            free (args_info->system_orig); /* free previous string */
          args_info->system_orig = gengetopt_strdup (optarg);
          break;

        case 'X':	/* Size in x.  */
          if (local_args_info.dim_x_given || (check_ambiguity && args_info->dim_x_given))
            {
              fprintf (stderr, "%s: `--dim-x' (`-X') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dim_x_given && ! override)
            continue;
          local_args_info.dim_x_given = 1;
          args_info->dim_x_given = 1;
          args_info->dim_x_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->dim_x_orig)
            free (args_info->dim_x_orig); /* free previous string */
          args_info->dim_x_orig = gengetopt_strdup (optarg);
          break;

        case 'Y':	/* Size in y.  */
          if (local_args_info.dim_y_given || (check_ambiguity && args_info->dim_y_given))
            {
              fprintf (stderr, "%s: `--dim-y' (`-Y') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dim_y_given && ! override)
            continue;
          local_args_info.dim_y_given = 1;
          args_info->dim_y_given = 1;
          args_info->dim_y_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->dim_y_orig)
            free (args_info->dim_y_orig); /* free previous string */
          args_info->dim_y_orig = gengetopt_strdup (optarg);
          break;

        case 'Z':	/* Size in z.  */
          if (local_args_info.dim_z_given || (check_ambiguity && args_info->dim_z_given))
            {
              fprintf (stderr, "%s: `--dim-z' (`-Z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dim_z_given && ! override)
            continue;
          local_args_info.dim_z_given = 1;
          args_info->dim_z_given = 1;
          args_info->dim_z_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->dim_z_orig)
            free (args_info->dim_z_orig); /* free previous string */
          args_info->dim_z_orig = gengetopt_strdup (optarg);
          break;

        case 'T':	/* Duration.  */
          if (local_args_info.dim_t_given || (check_ambiguity && args_info->dim_t_given))
            {
              fprintf (stderr, "%s: `--dim-t' (`-T') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dim_t_given && ! override)
            continue;
          local_args_info.dim_t_given = 1;
          args_info->dim_t_given = 1;
          args_info->dim_t_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->dim_t_orig)
            free (args_info->dim_t_orig); /* free previous string */
          args_info->dim_t_orig = gengetopt_strdup (optarg);
          break;

        case '5':	/* Scaling factor in x.  */
          if (local_args_info.fac_x_given || (check_ambiguity && args_info->fac_x_given))
            {
              fprintf (stderr, "%s: `--fac-x' (`-5') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->fac_x_given && ! override)
            continue;
          local_args_info.fac_x_given = 1;
          args_info->fac_x_given = 1;
          args_info->fac_x_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->fac_x_orig)
            free (args_info->fac_x_orig); /* free previous string */
          args_info->fac_x_orig = gengetopt_strdup (optarg);
          break;

        case '6':	/* Scaling factor in y.  */
          if (local_args_info.fac_y_given || (check_ambiguity && args_info->fac_y_given))
            {
              fprintf (stderr, "%s: `--fac-y' (`-6') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->fac_y_given && ! override)
            continue;
          local_args_info.fac_y_given = 1;
          args_info->fac_y_given = 1;
          args_info->fac_y_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->fac_y_orig)
            free (args_info->fac_y_orig); /* free previous string */
          args_info->fac_y_orig = gengetopt_strdup (optarg);
          break;

        case '7':	/* Scaling factor in z.  */
          if (local_args_info.fac_z_given || (check_ambiguity && args_info->fac_z_given))
            {
              fprintf (stderr, "%s: `--fac-z' (`-7') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->fac_z_given && ! override)
            continue;
          local_args_info.fac_z_given = 1;
          args_info->fac_z_given = 1;
          args_info->fac_z_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->fac_z_orig)
            free (args_info->fac_z_orig); /* free previous string */
          args_info->fac_z_orig = gengetopt_strdup (optarg);
          break;

        case '8':	/* Scaling factor in t.  */
          if (local_args_info.fac_t_given || (check_ambiguity && args_info->fac_t_given))
            {
              fprintf (stderr, "%s: `--fac-t' (`-8') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->fac_t_given && ! override)
            continue;
          local_args_info.fac_t_given = 1;
          args_info->fac_t_given = 1;
          args_info->fac_t_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->fac_t_orig)
            free (args_info->fac_t_orig); /* free previous string */
          args_info->fac_t_orig = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Origin for x.  */
          if (local_args_info.org_x_given || (check_ambiguity && args_info->org_x_given))
            {
              fprintf (stderr, "%s: `--org-x' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->org_x_given && ! override)
            continue;
          local_args_info.org_x_given = 1;
          args_info->org_x_given = 1;
          args_info->org_x_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->org_x_orig)
            free (args_info->org_x_orig); /* free previous string */
          args_info->org_x_orig = gengetopt_strdup (optarg);
          break;

        case 'p':	/* Origin for y.  */
          if (local_args_info.org_y_given || (check_ambiguity && args_info->org_y_given))
            {
              fprintf (stderr, "%s: `--org-y' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->org_y_given && ! override)
            continue;
          local_args_info.org_y_given = 1;
          args_info->org_y_given = 1;
          args_info->org_y_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->org_y_orig)
            free (args_info->org_y_orig); /* free previous string */
          args_info->org_y_orig = gengetopt_strdup (optarg);
          break;

        case 'q':	/* Origin for z.  */
          if (local_args_info.org_z_given || (check_ambiguity && args_info->org_z_given))
            {
              fprintf (stderr, "%s: `--org-z' (`-q') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->org_z_given && ! override)
            continue;
          local_args_info.org_z_given = 1;
          args_info->org_z_given = 1;
          args_info->org_z_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->org_z_orig)
            free (args_info->org_z_orig); /* free previous string */
          args_info->org_z_orig = gengetopt_strdup (optarg);
          break;

        case 'r':	/* Origin for t.  */
          if (local_args_info.org_t_given || (check_ambiguity && args_info->org_t_given))
            {
              fprintf (stderr, "%s: `--org-t' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->org_t_given && ! override)
            continue;
          local_args_info.org_t_given = 1;
          args_info->org_t_given = 1;
          args_info->org_t_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->org_t_orig)
            free (args_info->org_t_orig); /* free previous string */
          args_info->org_t_orig = gengetopt_strdup (optarg);
          break;

        case 'I':	/* Increment in x.  */
          if (local_args_info.inc_x_given || (check_ambiguity && args_info->inc_x_given))
            {
              fprintf (stderr, "%s: `--inc-x' (`-I') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->inc_x_given && ! override)
            continue;
          local_args_info.inc_x_given = 1;
          args_info->inc_x_given = 1;
          args_info->inc_x_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->inc_x_orig)
            free (args_info->inc_x_orig); /* free previous string */
          args_info->inc_x_orig = gengetopt_strdup (optarg);
          break;

        case 'J':	/* Increment in y.  */
          if (local_args_info.inc_y_given || (check_ambiguity && args_info->inc_y_given))
            {
              fprintf (stderr, "%s: `--inc-y' (`-J') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->inc_y_given && ! override)
            continue;
          local_args_info.inc_y_given = 1;
          args_info->inc_y_given = 1;
          args_info->inc_y_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->inc_y_orig)
            free (args_info->inc_y_orig); /* free previous string */
          args_info->inc_y_orig = gengetopt_strdup (optarg);
          break;

        case 'K':	/* Increment in z.  */
          if (local_args_info.inc_z_given || (check_ambiguity && args_info->inc_z_given))
            {
              fprintf (stderr, "%s: `--inc-z' (`-K') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->inc_z_given && ! override)
            continue;
          local_args_info.inc_z_given = 1;
          args_info->inc_z_given = 1;
          args_info->inc_z_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->inc_z_orig)
            free (args_info->inc_z_orig); /* free previous string */
          args_info->inc_z_orig = gengetopt_strdup (optarg);
          break;

        case 'L':	/* Increment in t.  */
          if (local_args_info.inc_t_given || (check_ambiguity && args_info->inc_t_given))
            {
              fprintf (stderr, "%s: `--inc-t' (`-L') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->inc_t_given && ! override)
            continue;
          local_args_info.inc_t_given = 1;
          args_info->inc_t_given = 1;
          args_info->inc_t_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->inc_t_orig)
            free (args_info->inc_t_orig); /* free previous string */
          args_info->inc_t_orig = gengetopt_strdup (optarg);
          break;

        case 'S':	/* Scaling factor for data.  */
          if (local_args_info.data_factor_given || (check_ambiguity && args_info->data_factor_given))
            {
              fprintf (stderr, "%s: `--data-factor' (`-S') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->data_factor_given && ! override)
            continue;
          local_args_info.data_factor_given = 1;
          args_info->data_factor_given = 1;
          args_info->data_factor_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->data_factor_orig)
            free (args_info->data_factor_orig); /* free previous string */
          args_info->data_factor_orig = gengetopt_strdup (optarg);
          break;

        case '0':	/* Origin for data scaling.  */
          if (local_args_info.data_zero_given || (check_ambiguity && args_info->data_zero_given))
            {
              fprintf (stderr, "%s: `--data-zero' (`-0') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->data_zero_given && ! override)
            continue;
          local_args_info.data_zero_given = 1;
          args_info->data_zero_given = 1;
          args_info->data_zero_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->data_zero_orig)
            free (args_info->data_zero_orig); /* free previous string */
          args_info->data_zero_orig = gengetopt_strdup (optarg);
          break;

        case 'A':	/* Author name with no spaces.  */
          if (local_args_info.author_given || (check_ambiguity && args_info->author_given))
            {
              fprintf (stderr, "%s: `--author' (`-A') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->author_given && ! override)
            continue;
          local_args_info.author_given = 1;
          args_info->author_given = 1;
          if (args_info->author_arg)
            free (args_info->author_arg); /* free previous string */
          args_info->author_arg = gengetopt_strdup (optarg);
          if (args_info->author_orig)
            free (args_info->author_orig); /* free previous string */
          args_info->author_orig = gengetopt_strdup (optarg);
          break;

        case '1':	/* Units for x.  */
          if (local_args_info.x_units_given || (check_ambiguity && args_info->x_units_given))
            {
              fprintf (stderr, "%s: `--x-units' (`-1') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->x_units_given && ! override)
            continue;
          local_args_info.x_units_given = 1;
          args_info->x_units_given = 1;
          if (args_info->x_units_arg)
            free (args_info->x_units_arg); /* free previous string */
          args_info->x_units_arg = gengetopt_strdup (optarg);
          if (args_info->x_units_orig)
            free (args_info->x_units_orig); /* free previous string */
          args_info->x_units_orig = gengetopt_strdup (optarg);
          break;

        case '2':	/* Units for y.  */
          if (local_args_info.y_units_given || (check_ambiguity && args_info->y_units_given))
            {
              fprintf (stderr, "%s: `--y-units' (`-2') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->y_units_given && ! override)
            continue;
          local_args_info.y_units_given = 1;
          args_info->y_units_given = 1;
          if (args_info->y_units_arg)
            free (args_info->y_units_arg); /* free previous string */
          args_info->y_units_arg = gengetopt_strdup (optarg);
          if (args_info->y_units_orig)
            free (args_info->y_units_orig); /* free previous string */
          args_info->y_units_orig = gengetopt_strdup (optarg);
          break;

        case '3':	/* Units for z.  */
          if (local_args_info.z_units_given || (check_ambiguity && args_info->z_units_given))
            {
              fprintf (stderr, "%s: `--z-units' (`-3') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->z_units_given && ! override)
            continue;
          local_args_info.z_units_given = 1;
          args_info->z_units_given = 1;
          if (args_info->z_units_arg)
            free (args_info->z_units_arg); /* free previous string */
          args_info->z_units_arg = gengetopt_strdup (optarg);
          if (args_info->z_units_orig)
            free (args_info->z_units_orig); /* free previous string */
          args_info->z_units_orig = gengetopt_strdup (optarg);
          break;

        case '4':	/* Units for t.  */
          if (local_args_info.t_units_given || (check_ambiguity && args_info->t_units_given))
            {
              fprintf (stderr, "%s: `--t-units' (`-4') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->t_units_given && ! override)
            continue;
          local_args_info.t_units_given = 1;
          args_info->t_units_given = 1;
          if (args_info->t_units_arg)
            free (args_info->t_units_arg); /* free previous string */
          args_info->t_units_arg = gengetopt_strdup (optarg);
          if (args_info->t_units_orig)
            free (args_info->t_units_orig); /* free previous string */
          args_info->t_units_orig = gengetopt_strdup (optarg);
          break;

        case 'j':	/* Make no. time slices jive with data size.  */
          if (local_args_info.jive_time_given || (check_ambiguity && args_info->jive_time_given))
            {
              fprintf (stderr, "%s: `--jive-time' (`-j') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->jive_time_given && ! override)
            continue;
          local_args_info.jive_time_given = 1;
          args_info->jive_time_given = 1;
          break;

        case 'e':	/* Transparent pixel value in hex.  */
          if (local_args_info.transparent_given || (check_ambiguity && args_info->transparent_given))
            {
              fprintf (stderr, "%s: `--transparent' (`-e') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->transparent_given && ! override)
            continue;
          local_args_info.transparent_given = 1;
          args_info->transparent_given = 1;
          if (args_info->transparent_arg)
            free (args_info->transparent_arg); /* free previous string */
          args_info->transparent_arg = gengetopt_strdup (optarg);
          if (args_info->transparent_orig)
            free (args_info->transparent_orig); /* free previous string */
          args_info->transparent_orig = gengetopt_strdup (optarg);
          break;

        case 'E':	/* Turn transparency off.  */
          if (local_args_info.no_transparent_given || (check_ambiguity && args_info->no_transparent_given))
            {
              fprintf (stderr, "%s: `--no-transparent' (`-E') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->no_transparent_given && ! override)
            continue;
          local_args_info.no_transparent_given = 1;
          args_info->no_transparent_given = 1;
          break;

        case 'D':	/* Remove header.  */
          if (local_args_info.decapitate_given || (check_ambiguity && args_info->decapitate_given))
            {
              fprintf (stderr, "%s: `--decapitate' (`-D') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->decapitate_given && ! override)
            continue;
          local_args_info.decapitate_given = 1;
          args_info->decapitate_given = 1;
          break;

        case 'c':	/* Add a line of comment.  */
          if (local_args_info.comment_given || (check_ambiguity && args_info->comment_given))
            {
              fprintf (stderr, "%s: `--comment' (`-c') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->comment_given && ! override)
            continue;
          local_args_info.comment_given = 1;
          args_info->comment_given = 1;
          if (args_info->comment_arg)
            free (args_info->comment_arg); /* free previous string */
          args_info->comment_arg = gengetopt_strdup (optarg);
          if (args_info->comment_orig)
            free (args_info->comment_orig); /* free previous string */
          args_info->comment_orig = gengetopt_strdup (optarg);
          break;

        case 'C':	/* Clear all comments.  */
          if (local_args_info.clear_comment_given || (check_ambiguity && args_info->clear_comment_given))
            {
              fprintf (stderr, "%s: `--clear-comment' (`-C') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->clear_comment_given && ! override)
            continue;
          local_args_info.clear_comment_given = 1;
          args_info->clear_comment_given = 1;
          break;

        case 'f':	/* output file.  */
          if (local_args_info.output_file_given || (check_ambiguity && args_info->output_file_given))
            {
              fprintf (stderr, "%s: `--output-file' (`-f') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_file_given && ! override)
            continue;
          local_args_info.output_file_given = 1;
          args_info->output_file_given = 1;
          if (args_info->output_file_arg)
            free (args_info->output_file_arg); /* free previous string */
          args_info->output_file_arg = gengetopt_strdup (optarg);
          if (args_info->output_file_orig)
            free (args_info->output_file_orig); /* free previous string */
          args_info->output_file_orig = gengetopt_strdup (optarg);
          break;

        case 'F':	/* attach header to this file.  */
          if (local_args_info.frankenstein_given || (check_ambiguity && args_info->frankenstein_given))
            {
              fprintf (stderr, "%s: `--frankenstein' (`-F') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->frankenstein_given && ! override)
            continue;
          local_args_info.frankenstein_given = 1;
          args_info->frankenstein_given = 1;
          if (args_info->frankenstein_arg)
            free (args_info->frankenstein_arg); /* free previous string */
          args_info->frankenstein_arg = gengetopt_strdup (optarg);
          if (args_info->frankenstein_orig)
            free (args_info->frankenstein_orig); /* free previous string */
          args_info->frankenstein_orig = gengetopt_strdup (optarg);
          break;

        case 'l':	/* explode file into igb time slices.  */
          if (local_args_info.explode_given || (check_ambiguity && args_info->explode_given))
            {
              fprintf (stderr, "%s: `--explode' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->explode_given && ! override)
            continue;
          local_args_info.explode_given = 1;
          args_info->explode_given = 1;
          break;

        case 'm':	/* convert igb to memfem format.  */
          if (local_args_info.memfeminize_given || (check_ambiguity && args_info->memfeminize_given))
            {
              fprintf (stderr, "%s: `--memfeminize' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->memfeminize_given && ! override)
            continue;
          local_args_info.memfeminize_given = 1;
          args_info->memfeminize_given = 1;
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
